### ISSUE TITLE
No more caspa camera support in  kernel for Overo

### ISSUE THREAD

**Issue by adegroote** [gumstix/meta-gumstix#14]
For an user perspective, the non-support for caspa camera in the new overo kernel (3.17.x in the dizzy branch) is a regression. 

I know that caspa support is still not in the mainstream kernel, but it would be nice if you can reenable caspa support in the 3.17 kernel, so users can benefit from modern kernel, with device tree and all, and is able to use caspa camera.

**Comment by ashcharles** [comment]
Agreed---I'd definitely like to get Caspa supported.  After the discussion [1], I was able to get caspa working on the suggested linux-media branch with these two WIP patches [2,3].  I haven't had a chance to try backporting these to 3.17 but this is a first start at least.

[1] https://www.marc.info/?t=142057700300004&r=1&w=3
[2] http://gumstix-misc.s3.amazonaws.com/patches/0001-First-cut-at-caspa-support-with-devicetree.patch
[3] http://gumstix-misc.s3.amazonaws.com/patches/0002-Pulling-in.patch

**Comment by adegroote** [comment]
I rebased the stack of patch on top on 3.17.8 on https://github.com/adegroote/linux/tree/linux-stable-caspa-3.17.y. I'm able to configure the camera and grab some images, through the image is a bit strange.

**Comment by ashcharles** [comment]
Awesome---I'll give it a go.  Thanks for testing :)

**Comment by ashcharles** [comment]
pushed linux-capsa-3.18 kernel (see a3b0cb1277e70960fbcdea35c8b8240f53be3e99)
