### ISSUE TITLE
Issue in grabbing linux-caspa kernel

### ISSUE THREAD

**Issue by adegroote** [gumstix/meta-gumstix#15]
I'm trying to test the linux-caspa kernel, so I uncommented the line

PREFERRED_PROVIDER_virtual/kernel = "linux-caspa"

When I try to build a core-minimal-image, the checkout target fails with 

```
error: pathspec 'master' did not match any file(s) known to git.
+ bb_exit_handler
+ ret=1
+ echo WARNING: exit code 1 from a shell command.
WARNING: exit code 1 from a shell command.
```

The full log message from bitbake -v linux-caspa is available on 

http://homepages.laas.fr/~adegroot/log.do_kernel_checkout.23126

Any help is welcome.

**Comment by adam-lee** [comment]
I don't believe we got Caspa working in the new device tree enabled Kernel [1]. It's work-in-progress.

[1] https://github.com/gumstix/meta-gumstix/commit/a3b0cb1277e70960fbcdea35c8b8240f53be3e99

**Comment by adam-lee** [comment]
Can you build just the kernel however? `bitbake virtual/kernel` ?

**Comment by ashcharles** [comment]
I tried this on my setup but wasn't able to recreate the issue.  Based on
your log, it looks like a failure fetching the kernel branch but the
requested 'v3.18-caspa-wip' branch seems available at the SRC_URI
repository: https://github.com/gumstix/linux/commits/v3.18-caspa-wip

In any case, I uncommented the line, built a console image with the extra
packages supporting caspa and posted here:
https://catalina.gumstix.com/binaries/1666/

Try the little script built-in to start raw streaming (just scripts the
magic commands from [1])
**overo side**
$ caspa-stream-raw <ip of desktop>

**desktop side**
$ gst-launch -v udpsrc port=5000 caps="application/x-rtp,
media=(string)video, clock-rate=(int)90000, encoding-name=(string)RAW,
sampling=(string)YCbCr-4:2:2, depth=(string)8, width=(string)752,
height=(string)480, colorimetry=(string)SMPTE240M, payload=(int)96" !
rtpvrawdepay ! xvimagesink

Let me know if it works for you.

[1]
https://github.com/gumstix/Gumstix-YoctoProject-Repo/wiki/Gstreamer-and-Caspa

**Comment by adegroote** [comment]
It fails because it tries, at some point, to fetch master branch, which doesn't exist on your kernel repo. I will try to upgrade the yocto core to see if this behaviour has been changed.

**Comment by ashcharles** [comment]
This is a bit of a pedestrian solution but I've switched the name from
'mainline' to 'master'---this seems more standard in any case.

**Comment by adegroote** [comment]
Thanks. I can confirm that I'm now able to build properly the linux-caspa. I will do some test as soon as I find a new connecter for my caspa.

**Comment by ashcharles** [comment]
closing as the fetcher is reported working.
